
const { Pool } = require("pg");

// ============================================================
// CONFIGURAÇÃO
// ============================================================

if (!process.env.DATABASE_URL) {
    require("dotenv").config();
}

if (!process.env.DATABASE_URL) {
    throw new Error(
        "❌ DATABASE_URL não encontrada no arquivo .env."
    );
}

const pool = new Pool({
    connectionString: process.env.DATABASE_URL,
    ssl: {
        rejectUnauthorized: false,
    },
});

// ============================================================
// CRIAR / VERIFICAR ESTRUTURA
// ============================================================

async function criarEstrutura(client) {

    console.log("");
    console.log("============================================");
    console.log("🗄️ VERIFICANDO ESTRUTURA POSTGRESQL");
    console.log("============================================");

    // ========================================================
    // USUÁRIOS
    // ========================================================

    await client.query(`
        CREATE TABLE IF NOT EXISTS usuarios (
            id TEXT PRIMARY KEY,
            nome TEXT,
            email TEXT,
            senha TEXT,
            tipo TEXT,
            restaurante_id TEXT,
            telefone TEXT,
            cpf TEXT,
            endereco JSONB,
            criado_em TIMESTAMPTZ,
            atualizado_em TIMESTAMPTZ,
            dados JSONB NOT NULL DEFAULT '{}'::jsonb
        );
    `);

    console.log("✅ usuarios");

    // ========================================================
    // RESTAURANTES
    // ========================================================

    await client.query(`
        CREATE TABLE IF NOT EXISTS restaurantes (
            id TEXT PRIMARY KEY,
            nome TEXT,
            cnpj TEXT,
            categoria TEXT,
            email TEXT,
            telefone TEXT,
            responsavel TEXT,
            cpf TEXT,
            endereco JSONB,
            pagamento JSONB,
            status TEXT,
            online BOOLEAN,
            aberto BOOLEAN,
            imagem TEXT,
            criado_em TIMESTAMPTZ,
            atualizado_em TIMESTAMPTZ,
            dados JSONB NOT NULL DEFAULT '{}'::jsonb
        );
    `);

    console.log("✅ restaurantes");

    // ========================================================
    // PRODUTOS
    // ========================================================

    await client.query(`
        CREATE TABLE IF NOT EXISTS produtos (
            id TEXT PRIMARY KEY,
            restaurante_id TEXT,
            nome TEXT,
            descricao TEXT,
            preco NUMERIC(12,4),
            categoria TEXT,
            disponivel BOOLEAN,
            destaque BOOLEAN,
            imagem TEXT,
            criado_em TIMESTAMPTZ,
            atualizado_em TIMESTAMPTZ,
            dados JSONB NOT NULL DEFAULT '{}'::jsonb
        );
    `);

    console.log("✅ produtos");

    // ========================================================
    // PEDIDOS
    // ========================================================

    await client.query(`
        CREATE TABLE IF NOT EXISTS pedidos (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            cliente_id TEXT,
            restaurante_id TEXT,
            itens JSONB NOT NULL DEFAULT '[]'::jsonb,
            endereco JSONB,
            pagamento TEXT,
            pagamento_status TEXT,
            status_pagamento TEXT,
            pagamento_aprovado BOOLEAN,
            subtotal NUMERIC(12,4),
            taxa_servico NUMERIC(12,4),
            taxa_entrega NUMERIC(12,4),
            total NUMERIC(12,4),
            precisa_troco BOOLEAN,
            troco_para NUMERIC(12,4),
            valor_troco NUMERIC(12,4),
            external_reference TEXT,
            referencia_pagamento TEXT,
            status TEXT,
            suporte JSONB,
            criado_em TIMESTAMPTZ,
            atualizado_em TIMESTAMPTZ,
            dados JSONB NOT NULL DEFAULT '{}'::jsonb
        );
    `);

    console.log("✅ pedidos");

    // ========================================================
    // ENTREGADORES
    // ========================================================

    await client.query(`
        CREATE TABLE IF NOT EXISTS entregadores (
            id TEXT PRIMARY KEY,
            nome TEXT,
            email TEXT,
            telefone TEXT,
            cpf TEXT,
            status TEXT,
            online BOOLEAN,
            dados JSONB NOT NULL DEFAULT '{}'::jsonb
        );
    `);

    console.log("✅ entregadores");

    // ========================================================
    // PAGAMENTOS
    // ========================================================

    await client.query(`
        CREATE TABLE IF NOT EXISTS pagamentos (
            id TEXT PRIMARY KEY,
            pedido_id TEXT,
            status TEXT,
            valor NUMERIC(12,4),
            dados JSONB NOT NULL DEFAULT '{}'::jsonb,
            criado_em TIMESTAMPTZ
        );
    `);

    console.log("✅ pagamentos");

    // ========================================================
    // PAGAMENTOS ASAAS
    // ========================================================

    await client.query(`
        CREATE TABLE IF NOT EXISTS pagamentos_asaas (
            id TEXT PRIMARY KEY,
            pagamento_id TEXT,
            pedido_id TEXT,
            external_reference TEXT,
            status TEXT,
            valor NUMERIC(12,4),
            dados JSONB NOT NULL DEFAULT '{}'::jsonb,
            criado_em TIMESTAMPTZ,
            atualizado_em TIMESTAMPTZ
        );
    `);

    console.log("✅ pagamentos_asaas");

    // ========================================================
    // PROMOÇÕES
    // ========================================================

    await client.query(`
        CREATE TABLE IF NOT EXISTS promocoes (
            id TEXT PRIMARY KEY,
            restaurante_id TEXT,
            produto_id TEXT,
            titulo TEXT,
            descricao TEXT,
            preco_original NUMERIC(12,4),
            preco_promocional NUMERIC(12,4),
            desconto NUMERIC(12,4),
            inicio TIMESTAMPTZ,
            fim TIMESTAMPTZ,
            ativa BOOLEAN,
            criado_em TIMESTAMPTZ,
            dados JSONB NOT NULL DEFAULT '{}'::jsonb
        );
    `);

    console.log("✅ promocoes");

    // ========================================================
    // FAVORITOS
    // ========================================================

    await client.query(`
        CREATE TABLE IF NOT EXISTS favoritos (
            id TEXT PRIMARY KEY,
            usuario_id TEXT,
            restaurante_id TEXT,
            nome TEXT,
            descricao TEXT,
            avaliacao TEXT,
            logo TEXT,
            dados JSONB NOT NULL DEFAULT '{}'::jsonb
        );
    `);

    console.log("✅ favoritos");

    // ========================================================
    // CARTEIRAS DOS ENTREGADORES
    // ========================================================

    await client.query(`
        CREATE TABLE IF NOT EXISTS carteiras_entregadores (
            id BIGSERIAL PRIMARY KEY,

            entregador_id TEXT NOT NULL UNIQUE,

            saldo NUMERIC(12,4)
                NOT NULL DEFAULT 0,

            limite_negativo NUMERIC(12,4)
                NOT NULL DEFAULT 200,

            dinheiro_em_maos NUMERIC(12,4)
                NOT NULL DEFAULT 0,

            total_comissoes NUMERIC(12,4)
                NOT NULL DEFAULT 0,

            total_recebido_clientes NUMERIC(12,4)
                NOT NULL DEFAULT 0,

            total_devido_restaurante NUMERIC(12,4)
                NOT NULL DEFAULT 0,

            total_devido_foodjet NUMERIC(12,4)
                NOT NULL DEFAULT 0,

            criado_em TIMESTAMPTZ
                NOT NULL DEFAULT NOW(),

            atualizado_em TIMESTAMPTZ
                NOT NULL DEFAULT NOW(),

            dados JSONB
                NOT NULL DEFAULT '{}'::jsonb,

            CONSTRAINT fk_carteira_entregador
                FOREIGN KEY (entregador_id)
                REFERENCES entregadores(id)
                ON DELETE CASCADE
        );
    `);

    console.log("✅ carteiras_entregadores");

    // ========================================================
    // MOVIMENTAÇÕES DA CARTEIRA
    // ========================================================

    await client.query(`
        CREATE TABLE IF NOT EXISTS movimentacoes_carteira (
            id BIGSERIAL PRIMARY KEY,

            carteira_id BIGINT NOT NULL,

            entregador_id TEXT NOT NULL,

            pedido_id BIGINT,

            tipo TEXT NOT NULL,

            descricao TEXT,

            forma_pagamento TEXT,

            valor NUMERIC(12,4) NOT NULL,

            saldo_anterior NUMERIC(12,4) NOT NULL,

            saldo_posterior NUMERIC(12,4) NOT NULL,

            valor_restaurante NUMERIC(12,4)
                NOT NULL DEFAULT 0,

            valor_foodjet NUMERIC(12,4)
                NOT NULL DEFAULT 0,

            valor_entregador NUMERIC(12,4)
                NOT NULL DEFAULT 0,

            dinheiro_em_maos_anterior NUMERIC(12,4)
                NOT NULL DEFAULT 0,

            dinheiro_em_maos_posterior NUMERIC(12,4)
                NOT NULL DEFAULT 0,

            referencia TEXT,

            dados JSONB
                NOT NULL DEFAULT '{}'::jsonb,

            criado_em TIMESTAMPTZ
                NOT NULL DEFAULT NOW(),

            CONSTRAINT fk_movimentacao_carteira
                FOREIGN KEY (carteira_id)
                REFERENCES carteiras_entregadores(id)
                ON DELETE CASCADE,

            CONSTRAINT fk_movimentacao_entregador
                FOREIGN KEY (entregador_id)
                REFERENCES entregadores(id)
                ON DELETE CASCADE,

            CONSTRAINT fk_movimentacao_pedido
                FOREIGN KEY (pedido_id)
                REFERENCES pedidos(id)
                ON DELETE SET NULL
        );
    `);

    console.log("✅ movimentacoes_carteira");

    // ========================================================
    // ÍNDICES
    // ========================================================

    await client.query(`
        CREATE INDEX IF NOT EXISTS idx_carteiras_entregador
        ON carteiras_entregadores(entregador_id);
    `);

    await client.query(`
        CREATE INDEX IF NOT EXISTS idx_movimentacoes_carteira
        ON movimentacoes_carteira(carteira_id);
    `);

    await client.query(`
        CREATE INDEX IF NOT EXISTS idx_movimentacoes_entregador
        ON movimentacoes_carteira(entregador_id);
    `);

    await client.query(`
        CREATE INDEX IF NOT EXISTS idx_movimentacoes_pedido
        ON movimentacoes_carteira(pedido_id);
    `);

    await client.query(`
        CREATE INDEX IF NOT EXISTS idx_movimentacoes_criado
        ON movimentacoes_carteira(criado_em DESC);
    `);

    // ========================================================
    // REFERÊNCIA ÚNICA
    //
    // Impede que uma mesma movimentação financeira seja
    // lançada duas vezes por acidente.
    // ========================================================

    await client.query(`
        CREATE UNIQUE INDEX IF NOT EXISTS
        idx_movimentacoes_referencia_unica
        ON movimentacoes_carteira(
            entregador_id,
            referencia
        )
        WHERE referencia IS NOT NULL;
    `);

    console.log("✅ Índices financeiros");

    console.log("");
    console.log("🎯 Estrutura PostgreSQL verificada.");
}

// ============================================================
// GARANTIR CARTEIRAS DOS ENTREGADORES
// ============================================================

async function garantirCarteiras(client) {

    console.log("");
    console.log("============================================");
    console.log("💰 VERIFICANDO CARTEIRAS DOS ENTREGADORES");
    console.log("============================================");

    // ========================================================
    // CONTAR ENTREGADORES
    // ========================================================

    const entregadores =
        await client.query(`
            SELECT
                COUNT(*)::int AS total
            FROM entregadores
        `);

    const totalEntregadores =
        entregadores.rows[0].total;

    console.log(
        `🏍️ Entregadores encontrados: ${totalEntregadores}`
    );

    // ========================================================
    // CRIAR CARTEIRA PARA QUEM AINDA NÃO POSSUI
    // ========================================================

    const resultado =
        await client.query(`
            INSERT INTO carteiras_entregadores (
                entregador_id,
                saldo,
                limite_negativo,
                dinheiro_em_maos,
                total_comissoes,
                total_recebido_clientes,
                total_devido_restaurante,
                total_devido_foodjet
            )
            SELECT
                e.id,
                0,
                200,
                0,
                0,
                0,
                0,
                0
            FROM entregadores e
            LEFT JOIN carteiras_entregadores c
                ON c.entregador_id = e.id
            WHERE c.id IS NULL
            RETURNING id, entregador_id
        `);

    console.log(
        `💰 Novas carteiras criadas: ${resultado.rowCount}`
    );

    // ========================================================
    // CONTAR CARTEIRAS
    // ========================================================

    const carteiras =
        await client.query(`
            SELECT
                COUNT(*)::int AS total
            FROM carteiras_entregadores
        `);

    console.log(
        `💰 Carteiras existentes: ${carteiras.rows[0].total}`
    );

    // ========================================================
    // VERIFICAR ENTREGADORES SEM CARTEIRA
    // ========================================================

    const semCarteira =
        await client.query(`
            SELECT
                COUNT(*)::int AS total
            FROM entregadores e
            LEFT JOIN carteiras_entregadores c
                ON c.entregador_id = e.id
            WHERE c.id IS NULL
        `);

    const faltantes =
        semCarteira.rows[0].total;

    if (faltantes === 0) {

        console.log(
            "✅ Todos os entregadores possuem carteira."
        );

    } else {

        throw new Error(
            `❌ Existem ${faltantes} entregadores sem carteira.`
        );
    }
}

// ============================================================
// RESUMO DAS TABELAS
// ============================================================

async function mostrarResumo(client) {

    console.log("");
    console.log("============================================");
    console.log("📊 RESUMO ATUAL DO POSTGRESQL");
    console.log("============================================");

    const tabelas = [
        ["usuarios", "👥"],
        ["restaurantes", "🏪"],
        ["produtos", "🍕"],
        ["pedidos", "📦"],
        ["entregadores", "🏍️"],
        ["carteiras_entregadores", "💰"],
        ["movimentacoes_carteira", "📒"],
        ["pagamentos", "💳"],
        ["pagamentos_asaas", "💰"],
        ["promocoes", "🎟️"],
        ["favoritos", "❤️"],
    ];

    for (const [tabela, emoji] of tabelas) {

        const resultado =
            await client.query(`
                SELECT COUNT(*)::int AS total
                FROM ${tabela}
            `);

        console.log(
            `${emoji} ${tabela}: ${resultado.rows[0].total}`
        );
    }

    // ========================================================
    // RESUMO FINANCEIRO
    // ========================================================

    const financeiro =
        await client.query(`
            SELECT
                COUNT(*)::int AS entregadores,

                COALESCE(
                    SUM(saldo),
                    0
                ) AS saldo_total,

                COALESCE(
                    SUM(dinheiro_em_maos),
                    0
                ) AS dinheiro_em_maos,

                COALESCE(
                    SUM(total_comissoes),
                    0
                ) AS total_comissoes,

                COALESCE(
                    SUM(total_recebido_clientes),
                    0
                ) AS total_recebido_clientes,

                COALESCE(
                    SUM(total_devido_restaurante),
                    0
                ) AS total_devido_restaurante,

                COALESCE(
                    SUM(total_devido_foodjet),
                    0
                ) AS total_devido_foodjet

            FROM carteiras_entregadores
        `);

    const dados =
        financeiro.rows[0];

    console.log("");
    console.log("============================================");
    console.log("💰 RESUMO FINANCEIRO");
    console.log("============================================");

    console.log(
        "🏍️ Entregadores:",
        dados.entregadores
    );

    console.log(
        "💵 Saldo digital:",
        dados.saldo_total
    );

    console.log(
        "💰 Dinheiro em mãos:",
        dados.dinheiro_em_maos
    );

    console.log(
        "🟢 Total de comissões:",
        dados.total_comissoes
    );

    console.log(
        "💳 Total recebido de clientes:",
        dados.total_recebido_clientes
    );

    console.log(
        "🏪 Total devido aos restaurantes:",
        dados.total_devido_restaurante
    );

    console.log(
        "🟠 Total devido ao FoodJet:",
        dados.total_devido_foodjet
    );

    console.log("");
}

// ============================================================
// VERIFICAR POSTGRESQL
// ============================================================

async function verificarConexao(client) {

    const resultado =
        await client.query(`
            SELECT
                NOW() AS agora
        `);

    console.log(
        "✅ Conexão PostgreSQL OK."
    );

    console.log(
        "🕐 Banco:",
        resultado.rows[0].agora
    );
}

// ============================================================
// EXECUÇÃO PRINCIPAL
// ============================================================

async function migrar() {

    let client;

    try {

        console.log("");
        console.log("============================================");
        console.log("🚀 ATUALIZAÇÃO ESTRUTURAL FOODJET");
        console.log("============================================");

        console.log(
            "🐘 PostgreSQL será usado como fonte de dados."
        );

        console.log(
            "🚫 foodjet.json não será utilizado."
        );

        console.log("");

        // ====================================================
        // CONECTAR
        // ====================================================

        client =
            await pool.connect();

        await verificarConexao(
            client
        );

        // ====================================================
        // INICIAR TRANSAÇÃO
        // ====================================================

        await client.query(
            "BEGIN"
        );

        // ====================================================
        // CRIAR / VERIFICAR ESTRUTURA
        // ====================================================

        await criarEstrutura(
            client
        );

        // ====================================================
        // GARANTIR CARTEIRAS
        // ====================================================

        await garantirCarteiras(
            client
        );

        // ====================================================
        // COMMIT
        // ====================================================

        await client.query(
            "COMMIT"
        );

        console.log("");
        console.log("============================================");
        console.log("✅ ALTERAÇÕES CONFIRMADAS");
        console.log("============================================");

        // ====================================================
        // RESUMO
        // ====================================================

        await mostrarResumo(
            client
        );

        console.log("");
        console.log("============================================");
        console.log("🎉 ESTRUTURA FOODJET ATUALIZADA!");
        console.log("============================================");

    } catch (error) {

        if (client) {

            try {

                await client.query(
                    "ROLLBACK"
                );

                console.log(
                    "↩️ ROLLBACK executado."
                );

            } catch (rollbackError) {

                console.error(
                    "❌ Erro no ROLLBACK:",
                    rollbackError.message
                );
            }
        }

        console.error("");
        console.error(
            "❌ ERRO DURANTE A ATUALIZAÇÃO:"
        );

        console.error(
            error.message
        );

        console.error("");

        process.exitCode = 1;

    } finally {

        if (client) {
            client.release();
        }

        await pool.end();
    }
}

// ============================================================
// EXECUTAR
// ============================================================

migrar();

