name: foodjet
description: Aplicativo cliente FoodJet
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  lottie: ^3.3.1

  # Ícones padrão iOS
  cupertino_icons: ^1.0.8

  # Comunicação com API FoodJet
  http: ^1.2.2

  # Salvar login, usuário e sessão
  shared_preferences: ^2.5.5

  # Imagens da internet
  cached_network_image: ^3.4.1

  # Gerenciamento de estado (se já estiver usando)
  provider: ^6.1.2

  # Firebase (caso use Google Login futuramente)
  firebase_core: ^3.15.2
  firebase_auth: ^5.7.0
  google_sign_in: ^6.2.1
  socket_io_client: ^3.1.6


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0


flutter:

  uses-material-design: true

  assets:
    - assets/animations/foodjet_splash.json
    
   